### ISSUE TITLE
error: (-215:Assertion failed)

### ISSUE THREAD

**Issue by RobertLee0522** [yushulx/python-lite-camera#6]
Encountered some errors during execution.

> OpenCV version: 4.6.0
> 0: KS5A00N
> 1: KS5A00N
> Select a camera (0 to 1): 1
> Default width: 640.0, height: 480.0
> [ WARN:0@5.723] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (464) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072875772
> [ WARN:0@5.739] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (476) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072875772
> [ WARN:1@5.745] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1752) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072875772
> Traceback (most recent call last):
>   File "C:\Users\461100\Desktop\python-capture-device-list-master\test.py", line 68, in <module>
>     main()
>   File "C:\Users\461100\Desktop\python-capture-device-list-master\test.py", line 57, in main
>     cv2.imshow("frame", frame)
> cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion 
> failed) size.width>0 && size.height>0 in function 'cv::imshow

If you can provide any help, it will help me a lot, thank you very much.

**Comment by yushulx** [comment]
@RobertLee0522 it's an OpenCV capture issue. Are you using virtual camera?
